spring.application.name=hotelmanagementbackend
server.port=8090
spring.data.mongodb.uri=mongodb+srv://kroopa07012002_db_user:rmNFhWjOPNDUuK3C@cluster0.qro8gd8.mongodb.net/hotel_management_db?retryWrites=true&w=majority
spring.devtools.restart.enabled=false